### PR TITLE
fix one get endpoint with comment to explain to fred

### PR DESCRIPTION
**Pull request by nindyahapsari**
I fix the get endpoint for flight.
I also explain what I did in the comment and you can read through it by clicking the "Files Changed" tab (right side)

### CODE REVIEW

**Comment by nindyahapsari** [comment]
sigh....of course conflicts

**Comment by nindyahapsari** [comment]
fix the conflicts but need to make linter happy, so i will clean some of my code according to the linter *sigh*

**Comment by nindyahapsari** [comment]
adding test, proably will break something..im trying to mock the DB for testing purposes

**Comment by nindyahapsari** [comment]
Working on the test

**Review by Fred0202 — APPROVED** [review]

**Comment by nindyahapsari** [comment]
need to write more test but I will create separate branch for that

**Pull request merged**
